### ISSUE TITLE
.ovpn files are missing for PIA

### ISSUE THREAD

**Issue by the8thsign** [guillaumedsde/alpine-qbittorrent-openvpn#7]
After switching from qbittorrent-openvpn docker image to alpine-qbittorrent-openvpn, I'm getting the follow errors on startup:

2020-06-18T03:02:26.613925052Z Trying to use OpenVPN provider: PIA
2020-06-18T03:02:26.647451183Z Connecting to raw.githubusercontent.com (151.101.128.133:443)
2020-06-18T03:02:26.826554142Z wget: server returned error: HTTP/1.1 404 Not Found
2020-06-18T03:02:26.826780456Z ERROR: Could not find OpenVPN configuration for provider PIA at https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/CA.ovpn

**Comment by guillaumedsde** [comment]
Hi :wave: are you running the container with the `docker run` command?

**Comment by the8thsign** [comment]
I'm using docker-compose

**Comment by guillaumedsde** [comment]
could you post the service definition for the container in you compose file? (don't forget to redact sensitive sections :) )

**Comment by the8thsign** [comment]
qbittorrent-openvpn:
    image: guillaumedsde/alpine-qbittorrent-openvpn
    hostname: qbittorrent
    container_name: qbittorrent
    restart: always
    volumes:
      - $USERDIR/docker/qbittorrent-openvpn:/config
      - $USERDIR/downloads/qbittorrent:/downloads
    ports:
      - 8168:8168
      - 6881:6881
      - 6881:6881/udp
    environment:
        - CREATE_TUN_DEVICE=true
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=US New York City
        - OPENVPN_USERNAME=$PIA_USERNAME
        - OPENVPN_PASSWORD=$PIA_PASSWORD
        - WEBPROXY_ENABLED=false
        - WEBUI_PORT=8168
        - LAN=$LOCAL_NETWORK
        - PUID=1026
        - PGID=101
        - TZ=America/New_York
    cap_add:
        - NET_ADMIN
    mem_limit: "4096m"
    logging:
      driver: json-file
      options:
        max-size: "10m"
    networks:
      - traefik_proxy

**Comment by guillaumedsde** [comment]
alright, I think its fixed in a47b9b623c1f9ffa7633fc8c3284455f73f2c38f can you try again after pulling the latest image?

**Comment by guillaumedsde** [comment]
regarding the web ui port, I'll need to document this, but the variable name is now `QBT_WEBUI_PORT`

**Comment by the8thsign** [comment]
Ok, pulled the latest version. Now has a different error, 400 instead of 404.

2020-06-18T23:15:18.907917377Z Connecting to raw.githubusercontent.com (151.101.192.133:443)
2020-06-18T23:15:19.016059568Z wget: server returned error: HTTP/1.1 400 Bad Request
2020-06-18T23:15:19.016383730Z ERROR: Could not find OpenVPN configuration for provider PIA at https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/US New York City.ovpn

**Comment by the8thsign** [comment]
When changing the profile to just CA, back to a 404 error.

2020-06-18T23:29:18.333657045Z Trying to use OpenVPN provider: PIA
2020-06-18T23:29:18.354150993Z Connecting to raw.githubusercontent.com (151.101.192.133:443)
2020-06-18T23:29:18.423708858Z wget: server returned error: HTTP/1.1 404 Not Found
2020-06-18T23:29:18.423871851Z ERROR: Could not find OpenVPN configuration for provider PIA at https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/CA.ovpn
2020-06-18T23:29:18.424764070Z [cont-init.d] 02-setup-openvpn: exited 1.

**Comment by guillaumedsde** [comment]
found the issue, (I need to URL encode spaces) can you try pulling `latest` see if its resolved now?

**Comment by the8thsign** [comment]
Unfortunately the issue is still present for me.

2020-06-19T11:50:58.939579044Z [s6-init] making user provided files available at /var/run/s6/etc...exited 0.
2020-06-19T11:50:58.992475439Z [s6-init] ensuring user provided files have correct perms...exited 0.
2020-06-19T11:50:58.998347998Z [fix-attrs.d] applying ownership & permissions fixes...
2020-06-19T11:50:59.001194796Z [fix-attrs.d] done.
2020-06-19T11:50:59.002498317Z [cont-init.d] executing container initialization scripts...
2020-06-19T11:50:59.004437649Z [cont-init.d] 01-setup-permissions: executing... 
2020-06-19T11:50:59.543420487Z [cont-init.d] 01-setup-permissions: exited 0.
2020-06-19T11:50:59.544497757Z [cont-init.d] 02-setup-openvpn: executing... 
2020-06-19T11:50:59.553021091Z Fri Jun 19 11:50:59 2020 TUN/TAP device tun0 opened
2020-06-19T11:50:59.553150377Z Fri Jun 19 11:50:59 2020 Persist state set to: ON
2020-06-19T11:50:59.556724980Z Trying to use OpenVPN provider: PIA
2020-06-19T11:50:59.571819876Z Connecting to raw.githubusercontent.com (151.101.0.133:443)
2020-06-19T11:50:59.678059889Z wget: server returned error: HTTP/1.1 400 Bad Request
2020-06-19T11:50:59.678323214Z ERROR: Could not find OpenVPN configuration for provider PIA at https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/US New York City.ovpn
2020-06-19T11:50:59.679038160Z [cont-init.d] 02-setup-openvpn: exited 1.
2020-06-19T11:50:59.689832944Z [cont-finish.d] executing container finish scripts...
2020-06-19T11:50:59.691076156Z [cont-finish.d] done.
2020-06-19T11:50:59.691450250Z [s6-finish] waiting for services.
2020-06-19T11:50:59.896684553Z [s6-finish] sending all processes the TERM signal.
2020-06-19T11:51:02.902627591Z [s6-finish] sending all processes the KILL signal and exiting.

**Comment by guillaumedsde** [comment]
hum, I'll look elsewhere then it looks like that was not the issue

**Comment by guillaumedsde** [comment]
if you want, in the meantime you can download the configuration and mount it manually [as described here](https://github.com/guillaumedsde/alpine-qbittorrent-openvpn#custom-openvpn-config)

**Comment by the8thsign** [comment]
Thanks for the workaround and I appreciate your help with this.

Adding the .ovpn file manually gives me the following errors:
2020-06-19T14:33:59.559672811Z OpenVPN provider not set. Using configuration at /config/openvpn/config.ovpn
2020-06-19T14:33:59.560356852Z [cont-init.d] 02-setup-openvpn: exited 0.
2020-06-19T14:33:59.561549891Z [cont-init.d] 03-setup-iptables: executing... 
2020-06-19T14:33:59.805602241Z [cont-init.d] 03-setup-iptables: exited 0.
2020-06-19T14:33:59.806491730Z [cont-init.d] done.
2020-06-19T14:33:59.807483430Z [services.d] starting services
2020-06-19T14:33:59.818057414Z [services.d] done.
2020-06-19T14:33:59.836594087Z Options error: --ca fails with '/etc/openvpn/pia/ca.rsa.2048.crt': No such file or directory (errno=2)
2020-06-19T14:33:59.836647589Z Options error: --crl-verify fails with '/etc/openvpn/pia/crl.rsa.2048.pem': No such file or directory (errno=2)
2020-06-19T14:33:59.836660984Z Options error: Please correct these errors.
2020-06-19T14:33:59.836672998Z Use --help for more information.

Is there anything else I need to mount besides the config.ovpn file?

**Comment by guillaumedsde** [comment]
it seems like PIA includes their certificate in a different file, looking at [haugene's](https://github.com/haugene/docker-transmission-openvpn) container has the files pre-included, I am trying to avoid that and download the VPN configurations when the container is started to avoid making the Docker image bigger (looks like I might have to go back to including them...).

a quick fix is to download the missing [ca.rsa.2048.crt](https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/ca.rsa.2048.crt) and [ca.rsa.2048.pem](https://raw.githubusercontent.com/haugene/docker-transmission-openvpn/master/openvpn/pia/ca.rsa.2048.pem), run `chown 100:100` on both of them (the OpenVPN user) and mount them in `/etc/openvpn/pia/`

```
docker run \
   -v /path/to/ca.rsa.2048.pem:/etc/openvpn/pia/crl.rsa.2048.pem \
   -v /path/to/ca.rsa.2048.crt:/etc/openvpn/pia/crl.rsa.2048.crt \
   ...
```

I am looking into a script to make this automatic :)

**Comment by guillaumedsde** [comment]
This was easier than I thought, I've modified the script to download all required files (including certificates) for the given vpn provider in commit 78c3af8272c48a2c05cd912be240a91341b66ade once [this pipeline](https://gitlab.com/guillaumedsde/alpine-qbittorrent-openvpn/-/pipelines) succeeds, everything should (in theory) just work once you pull the `latest` image **without needing to add the files specificed in the post above**

**Comment by the8thsign** [comment]
Just tested and everything is working! I appreciate it al the hard work.

**Comment by guillaumedsde** [comment]
thank you for the help in debugging :)
